/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JOTI;

import javax.swing.JOptionPane;

/**
 * Form for listing and adding new sections
 * @author Andrew Whitelaw
 */
public class FrmSectionsForm extends javax.swing.JDialog {

    private static java.awt.Frame parentForm;

    /**
     * Creates new form SectionsForm
     *
     * @param parent Parent object
     * @param modal Boolean for Modality. True if modal
     */
    public FrmSectionsForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentForm = parent;
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        //SectionList mySection = myJam.getMySectionList();
        new SectionsManager().getSectionNames().forEach((str) -> {
            this.sectionListBox.add(str);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sectionListBox = new java.awt.List();
        newSectionName = new java.awt.TextField();
        btnAddDelete = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sectionListBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sectionListBoxMouseClicked(evt);
            }
        });
        sectionListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionListBoxActionPerformed(evt);
            }
        });

        newSectionName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newSectionNameFocusGained(evt);
            }
        });
        newSectionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSectionNameActionPerformed(evt);
            }
        });

        btnAddDelete.setLabel("button1");
        btnAddDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sectionListBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newSectionName, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addComponent(btnAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(newSectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(sectionListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSectionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSectionNameActionPerformed

    }//GEN-LAST:event_newSectionNameActionPerformed

    private void newSectionNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newSectionNameFocusGained
        this.btnAddDelete.setLabel("Add Section");
    }//GEN-LAST:event_newSectionNameFocusGained

    private void sectionListBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sectionListBoxMouseClicked
        this.btnAddDelete.setLabel("Delete Section");
        this.newSectionName.setText(this.sectionListBox.getSelectedItem());
    }//GEN-LAST:event_sectionListBoxMouseClicked

    private void sectionListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionListBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionListBoxActionPerformed

    private void btnAddDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeleteActionPerformed
        SectionsManager aSections = new SectionsManager();
        String newSection = this.newSectionName.getText();
        Sections aSect = new Sections(newSection);
        if (!newSection.isEmpty()) {
            if (this.btnAddDelete.getLabel().equals("Delete Section")) {
                Sections mySection = new SectionsManager().getSectionListfromName(newSection);
                aSections.deleteSection(mySection);
                JOptionPane.showMessageDialog(null, newSection + " has been deleted");
            } else {
                System.out.println(aSect.getMySectionName());
                if (aSections.getSectionList().contains(aSect)) {
                    JOptionPane.showMessageDialog(null, "That section name already exists","Error",JOptionPane.ERROR_MESSAGE);
                } else {
                    aSections.addNewSection(aSect);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnAddDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSectionsForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSectionsForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSectionsForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSectionsForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSectionsForm dialog = new FrmSectionsForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        parentForm.repaint();
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAddDelete;
    private java.awt.TextField newSectionName;
    private java.awt.List sectionListBox;
    // End of variables declaration//GEN-END:variables
}
