/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JOTI;

import java.util.List;

/**
 * Form for selecting a person, Returns the person object selected by the user.
 * @author Andrew Whitelaw
 */
public class FrmSelectPerson extends javax.swing.JDialog {

    /**
     * Creates new form frmSelectPerson
     */
    Person returnPerson;

    /**
     * Constructor for FrmSelectPerson
     * @param parent Parent frame object
     * @param modal  True if the form is to be modal
     */
    public FrmSelectPerson(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        returnPerson = new Person();
        this.initComponents();
        this.initFields();
        setVisible(true);
    }

    /**
     *  Method to return a value from the form
     * @return Person object chosen in the dialog
     */
    public Person showDialog() {
        return returnPerson;
    }

    private void updateForename() {
        String mySurname = this.cmbSurname.getSelectedItem().toString();
        //Clear the forename combo
        this.cmbForeName.removeAllItems();
        //Get the list of people
        PersonManager pers = new PersonManager();

        List<String> forenames = pers.getForenamesforSurname(mySurname);
        for (String str : forenames) {
            this.cmbForeName.addItem(str);
        }
    }

    private void updateSection() {
        String mySurname = this.cmbSurname.getSelectedItem().toString();
        if (this.cmbForeName.getSelectedItem() != null) {
            String myForename = this.cmbForeName.getSelectedItem().toString();
            //Clear the section drop-down
            this.cmbSection.removeAllItems();
            //Get the list of people
            PersonManager pers = new PersonManager();

            List<String> sections = pers.getSectionsforNames(myForename, mySurname);
            for (String str : sections) {
                this.cmbSection.addItem(str);
            }
        }
    }

    private void initFields() {
        PersonManager pers = new PersonManager();
        List<String> surnames = pers.getSurnameList();

        //Step through the List
        for (String str : surnames) {
            //add the surname to the combo
            this.cmbSurname.addItem(str);
        }
        this.cmbSurname.setSelectedItem(null);
        this.cmbSection.setSelectedItem(null);
        this.cmbForeName.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSurname = new javax.swing.JComboBox<>();
        cmbForeName = new javax.swing.JComboBox<>();
        cmbSection = new javax.swing.JComboBox<>();
        lblSurname = new javax.swing.JLabel();
        lblForename = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Person to remove");
        setIconImage(null);
        setLocationByPlatform(true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        cmbSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSurnameActionPerformed(evt);
            }
        });

        cmbForeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbForeNameActionPerformed(evt);
            }
        });

        lblSurname.setText("Surname");

        lblForename.setText("ForeName");

        lblSection.setText("Section");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblForename, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSection, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSurname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbForeName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSection, 0, 164, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbForeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblForename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSurnameActionPerformed
        if (this.cmbSurname.getSelectedItem() != null) {
            this.updateForename();
        }
    }//GEN-LAST:event_cmbSurnameActionPerformed

    private void cmbForeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbForeNameActionPerformed
        if (this.cmbForeName.getSelectedItem() != null) {
            this.updateSection();
        }

    }//GEN-LAST:event_cmbForeNameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        PersonManager mP = new PersonManager();
        String fore = this.cmbForeName.getSelectedItem().toString();
        String sur = this.cmbSurname.getSelectedItem().toString();
        String sect = this.cmbSection.getSelectedItem().toString();
        this.returnPerson = mP.getPerson(fore, sur, sect);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSelectPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSelectPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSelectPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSelectPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSelectPerson dialog = new FrmSelectPerson(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cmbForeName;
    private javax.swing.JComboBox<String> cmbSection;
    private javax.swing.JComboBox<String> cmbSurname;
    private javax.swing.JLabel lblForename;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSurname;
    // End of variables declaration//GEN-END:variables
}
